### ISSUE TITLE
go's tail module crashes at ~140 cluster scale

### ISSUE THREAD

**Issue by dry923** [cloud-bulldozer/osde2e-scale-wrapper#6]
During a large scale test in stage the following error was hit and caused the test to stop being able to provision clusters

```
2020/11/18 13:57:57 FATAL -- failed to create Watcher
goroutine 26 [running]:
runtime/debug.Stack(0xc0000bda10, 0x21, 0x0)
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x9d
github.com/hpcloud/tail/util.Fatal(0x246ba3f, 0x18, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/util/util.go:22 +0xc7
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc00055c5c0)
        /root/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify_tracker.go:231 +0x413
created by github.com/hpcloud/tail/watch.glob..func1
        /root/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify_tracker.go:54 +0x12c
```

**Comment by dry923** [comment]
Will be testing if this is an openfiles limit issue as osde2e does create a number of files per cluster which may put it above the default max of 1024

**Comment by dry923** [comment]
After spending the day messing with open file limits and inotify/max_user_watches the issue ended up being that /proc/sys/fs/inotify/max_user_instances was set to 128. When set it to 20000 I was able to hit ~2600 concurrent go tails before it hit other resource limitations.

Not closing this outright because I want to add a doc update for it. The value can be changed by running:

```
# sysctl user.max_inotify_instances=20000
```
